[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "water_column_sonar_annotation"
version = "25.5.0"
authors = [
  { name="Rudy Klucik", email="rudy.klucik@noaa.gov" },
]
maintainers = [
  { name="Rudy Klucik", email="rudy.klucik@noaa.gov" },
]
description = "Processing tool for working with water column sonar annotation data."
keywords = ["ocean", "sonar", "water column", "evr"]
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE-MIT"]

dependencies = [
    "aiobotocore==2.21.1",
    "avro==1.12.0",
    "echoregions==0.2.1",
    "fiona==1.10.1",
    "fsspec",
    "geopandas==1.0.1",
    "numpy==1.26.4",
    "pandas==2.2.3",
    "pooch==1.8.2",
    "pyarrow==18.1.0",
    "python-dotenv==1.1.0",
    "s3fs",
    "scipy==1.15.1",
    "setuptools",
    "shapely==2.0.3",
    "xarray==2025.3.1",
    "zarr==2.18.7",
]

[project.optional-dependencies]
dev = [
    "bandit[toml]==1.8.0",
    "bandit",
    "black==25.1.0",
    "build",
    "isort",
    "matplotlib",
    "pooch==1.8.2",
    "pre-commit",
    "pyinstaller",
    "pytest==8.3.5",
    "ruff",
    "tqdm",
    "twine",
]

[project.urls]
Homepage = "https://github.com/CI-CMG/water-column-sonar-annotation"
Issues = "https://github.com/CI-CMG/water-column-sonar-annotation/issues"

[tool.setuptools]
py-modules = []

[tool.bandit]
exclude_dirs = ["tests"]

[tool.pre-commit-hooks.bandit]
exclude = ["*/tests/*"]

[tool.isort]
known_first_party = "water_column_sonar_annotation"
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
combine_as_imports = true

[tool.black]
line-length = 88
